### ISSUE TITLE
Renaming of CAD Consoles

### ISSUE THREAD

**Issue by phillf** [phillf/openCad#10]
So I am going through and renaming the different CAD consoles to be more representative. In my next commit they won't be in sub-folders either, however I need a suggestion of the name of the civilian console. Here are the names for the others:

- Law Enforcement/Fire/EMS – mdt.php
- Dispatch – cad.php

I was also thinking about merging all the "responder" buttons on the launcher in to one but I think I am going to leave them separate because I think eventually I want to build in the capability of customisations (ie. maps, notice boards, etc...) on a per department basis.

**Comment by Ramius1701** [comment]
Civilian sounds just right and the changes you are already thinking of making are good

**Comment by justinfarmer14** [comment]
That or give users the options to have multiple departments but you can loop them all in one and create a separate one for larger communities

**Comment by phillf** [comment]
Users are able to be in multiple departments. Not sure how it's handled on the fronted though.

**Comment by ItsAGeekThing** [comment]
This issue was moved to StormlightTech/openCAD-php#6
