### ISSUE TITLE
SQL Query Error when Importing SQL Database

### ISSUE THREAD

**Issue by MrSmallZzy** [phillf/openCad#16]
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `issued_by` text CHARACTER SET latin1 ' at line 6

**Comment by ItsAGeekThing** [comment]
This issue was moved to StormlightTech/openCAD-php#18
