### ISSUE TITLE
Civilians 

### ISSUE THREAD

**Issue by justinfarmer14** [phillf/openCad#19]
Civilian are unable to register them selves I did what you suggested and formatted the database and imported the SQL file but still doesn't work

**Comment by phillf** [comment]
What is the error?

**Comment by phillf** [comment]
duplicates #18

**Comment by justinfarmer14** [comment]
https://youtu.be/odI3yAe5yRs

**Comment by justinfarmer14** [comment]
and in reference to issue #18 when updating the files on the webserver that error log became of it

**Comment by ItsAGeekThing** [comment]
This issue was moved to StormlightTech/openCAD-php#12
