### ISSUE TITLE
Trying to input your 'openCad_Initialization.sql'

### ISSUE THREAD

**Issue by DoJoMan18** [phillf/openCad#2]
I'm getting a error when I try to input your .sql file. Could you please help me?
---------Dutch--------
Fout
SQL-query:

CREATE DATABASE IF NOT EXISTS "opencad"
MySQL meldt: Documentatie

#1064 - Er is iets fout in de gebruikte syntax bij '"opencad"' in regel 1

---------English [Translated]--------
Error
SQL-query:

CREATE DATABASE IF NOT EXISTS "opencad"
MySQL Reports: Documentation

#1064 - There is something wrong in the syntax used '"opencad"' on line 1

------

**Comment by DoJoMan18** [comment]
Got it! 
Instead of 

CREATE DATABASE IF NOT EXISTS "opencad"; USE "opencad"

use:

CREATE DATABASE IF NOT EXISTS `opencad`; USE `opencad`

**Comment by phillf** [comment]
#

**Comment by justinfarmer14** [comment]
a simple fix was to rename this to the data base that is already set up as in webhost dont give you a spefic option

**Comment by ItsAGeekThing** [comment]
This issue was moved to StormlightTech/openCAD-php#19
