### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by XxROBOTICSxX** [phillf/openCad#21]
Would you be able to update the Readme with proper installation instructions, requirements, and information on how to create the first user account/admin accounts.

**Comment by justinfarmer14** [comment]
[proposed install intrustctions.txt](https://github.com/phillf/openCad/files/1272626/proposed.install.intrustctions.txt)

**Comment by phillf** [comment]
@justinfarmer14 I like your idea for a YouTube video. FYI #23 will alleviate some of the potential difficulty with install and config.

**Comment by ItsAGeekThing** [comment]
This issue was moved to StormlightTech/openCAD-php#22
