### ISSUE TITLE
Status Bug

### ISSUE THREAD

**Issue by MinnesotaJames** [phillf/openCad#3]
Currently trying to resolve an issue related to setting your status available verse unavailable. Screenshot provided below. 

[![Screenshot from Gyazo](https://gyazo.com/542f7e0778b25dcb67158c12c6bbf042/raw)](https://gyazo.com/542f7e0778b25dcb67158c12c6bbf042)

Maybe because of how the SQL is set the statuses table is null.

**Comment by ItsAGeekThing** [comment]
This issue was moved to StormlightTech/openCAD-php#24
