### ISSUE TITLE
Citizens request

### ISSUE THREAD

**Issue by justinfarmer14** [phillf/openCad#4]
Citizens aren't able to submit identity requests

**Comment by phillf** [comment]
This was recently fixed with the newest version of [openCad_Initialization.sql](https://github.com/phillf/openCad/blob/18953bea70aefbe0566afb19473858121ab93be8/HIDE/openCad_Initialization.sql)

**Comment by ItsAGeekThing** [comment]
This issue was moved to StormlightTech/openCAD-php#20
