### ISSUE TITLE
Adding subusers

### ISSUE THREAD

**Issue by justinfarmer14** [phillf/openCad#5]
Issues adding assigned users to additional departments

**Comment by justinfarmer14** [comment]
![user groups 1](https://user-images.githubusercontent.com/31464982/29857522-b543dc36-8d1e-11e7-8800-b9544b7a05ba.png)

a work around i found was copying the head admin department id since i assigned all departments to my self

**Comment by ItsAGeekThing** [comment]
This issue was moved to StormlightTech/openCAD-php#2
