### ISSUE TITLE
Ncic actions 

### ISSUE THREAD

**Issue by justinfarmer14** [phillf/openCad#8]
unable to edit any of user data in ncic data base 
![ncic error edit](https://user-images.githubusercontent.com/31464982/29857463-67131464-8d1e-11e7-8486-7b716ce0f575.png)

**Comment by Ramius1701** [comment]
While i am able to edit after clicking the edit button the adminActions.php is blank and nothing changes

**Comment by ItsAGeekThing** [comment]
This issue was moved to StormlightTech/openCAD-php#4
