### ISSUE TITLE
Police Page wont open

### ISSUE THREAD

**Issue by Dooms192** [phillf/openCad#9]
Every time I try and open the Police page (responder.php) it signs me out. Is this common?

**Comment by DoJoMan18** [comment]
Only the Police? Because I have it with EMS, Fire, Highway, Police and Sheriff

**Comment by Dooms192** [comment]
Yep, same for all of them. Dispatch works though.

**Comment by Ramius1701** [comment]
Is this producing an error of any sort?

**Comment by justinfarmer14** [comment]
mines working properly

**Comment by DoJoMan18** [comment]
@Ramius1701 No its just signs you out. I think its something the do with the responder.php

**Comment by phillf** [comment]
It's something to do with the permission checking in responder.php. I took
out the code that handles that on my test server and responder.php works.

**Comment by DoJoMan18** [comment]
@phillf Do you have that file for me or can you tell me what part I should remove?

**Comment by ItsAGeekThing** [comment]
This issue was moved to StormlightTech/openCAD-php#5
